'use client';
import HomePage from "@/components/HomePage";
import React from "react";

export default function Home() {
    React.useEffect(()=>{
        localStorage.setItem('survey-schema', JSON.stringify({"pages":[{"name":"page1","elements":[{"type":"html","name":"question22","html":"<h3>Registration for Common EPR Registration</h3>"},{"type":"text","name":"question19","title":"GST Number *"},{"type":"html","name":"question14","html":"<h4>Company Details</h4>"},{"type":"text","name":"question1","title":"Legal Name*"},{"type":"text","name":"question2","startWithNewLine":false,"title":"Trade Name *"},{"type":"text","name":"question3","startWithNewLine":false,"title":"Type of Business*"},{"type":"text","name":"question4","title":"Type of Company *"},{"type":"text","name":"question5","startWithNewLine":false,"title":"Registered Address *"},{"type":"text","name":"question6","title":"Company PAN Card Number*"},{"type":"text","name":"question7","startWithNewLine":false,"title":"Company CIN Number *"},{"type":"html","name":"question20","html":"<h4>Authorised Person Details</h4>"},{"type":"text","name":"question8","title":"Name and Designation *"},{"type":"text","name":"question9","startWithNewLine":false,"title":"Mobile Number *"},{"type":"text","name":"question10","startWithNewLine":false,"title":"PAN Details *"},{"type":"text","name":"question16","title":"Email ID *"},{"type":"text","name":"question17","startWithNewLine":false,"title":"Password *"},{"type":"html","name":"question21","html":"<h4>Documents Required For Signup</h4>"}]}],"headerView":"advanced"}));
        localStorage.setItem("survey-schemass", JSON.stringify({"pages":[{"name":"page1","elements":[{"type":"dropdown","name":"question1","title":"Application Type","choices":[{"value":"Item 1","text":"Producers"},{"value":"Item 2","text":"Importers"},{"value":"Item 3","text":"Brand Owners"},{"value":"Item 4","text":"Recyclers (PWP)"}]},{"type":"dropdown","name":"question2","title":"Select State *","choices":[{"value":"Item 1","text":"Andhra Pradesh"},{"value":"Item 2","text":"Arunachal Pradesh"},{"value":"Item 3","text":"Assam"},{"value":"Item 4","text":"Bihar"},{"value":"Item 5","text":"Karnataka"}]},{"type":"dropdown","name":"question3","startWithNewLine":false,"title":"Do you have a Production Facility*","choices":[{"value":"Item 1","text":"yes"},{"value":"Item 2","text":"no"}]},{"type":"text","name":"question4","title":"Is the Production Facility Registered with District? *"},{"type":"text","name":"question5","startWithNewLine":false,"title":"Total Capital Invested in the Project ( Rs in Crores)*"},{"type":"text","name":"question6","title":"Year of Commencement of Operations*"},{"type":"text","name":"question9","title":"Status of Compliance with PWM Rules *"},{"type":"text","name":"question10","title":"Thickness of Plastic Packaing*"},{"type":"file","name":"question7","title":"Details (Type & Quantity) of Products Produced / Marketed "},{"type":"file","name":"question8","startWithNewLine":false,"title":"Responsive Picture of Plastic Package"}],"title":"Additional Details"}],"headerView":"advanced"}))
    })
  return (
    <div>
      <HomePage />
    </div>
  );
}
